version: v4-r{build}
pull_requests:
  do_not_increment_build_number: true
max_jobs: 2
skip_branch_with_pr: true
image: Visual Studio 2017
branches:
  only:
  - master
  - /^v4-r\d+$/
configuration:
- Debug
- Release
platform: Win32
clone_folder: c:\github\NoCheatZ-4
install:
- ps: >-
    git submodule update --init --recursive

    cd c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    Start-FileDownload "https://github.com/google/protobuf/archive/v2.5.0.zip"

    Expand-Archive v2.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\

    del v2.5.0.zip

    cd protobuf-2.5.0\

    Start-FileDownload "https://github.com/google/googletest/archive/release-1.5.0.zip"

    Expand-Archive release-1.5.0.zip -DestinationPath c:\github\NoCheatZ-4\server-plugin\SourceSdk\Interfaces\Protobuf\protobuf-2.5.0\

    del release-1.5.0.zip

    Rename-Item googletest-release-1.5.0 gtest

    cd c:\github\NoCheatZ-4\scripts

    C:\Python36\python.exe version.py
build:
  project: nocheatz.sln
  parallel: true
  verbosity: minimal
after_build:
- ps: >-
    $ErrorActionPreference = 'SilentlyContinue'

    $p0 = $env:configuration + "\*"

    $p3 = $env:configuration + "-Windows.zip"

    $p1 = "out\" + $p3

    $p2 = "Builds\" + $p1

    cd c:\github\NoCheatZ-4\Builds

    Get-ChildItem c:\github\NoCheatZ-4\Builds -Include *.exp -Recurse | foreach ($_) {Remove-Item $_.fullname}

    Get-ChildItem c:\github\NoCheatZ-4\Builds -Include *.ilk -Recurse | foreach ($_) {Remove-Item $_.fullname}

    Get-ChildItem c:\github\NoCheatZ-4\Builds -Include *.lib -Recurse | foreach ($_) {Remove-Item $_.fullname}

    Get-ChildItem c:\github\NoCheatZ-4\Builds -Include *.bsc -Recurse | foreach ($_) {Remove-Item $_.fullname}

    Get-ChildItem c:\github\NoCheatZ-4\Builds -Include .gitignore -Recurse | foreach ($_) {Remove-Item $_.fullname}

    New-Item -ItemType directory -Path out

    Compress-Archive -Path $p0 -DestinationPath $p1

    cd ..

    Push-AppveyorArtifact $p2 -FileName $p3 -DeploymentName deploy-out
deploy:
- provider: GitHub
  tag: $(appveyor_repo_tag_name)
  release: NoCheatZ $(appveyor_repo_tag_name)
  auth_token:
    secure: cmeI5Mwc+kiqp/KVpsM++TVOdsmMhb1jIAnW9oeV27mxuQpiHD5uu1zlHCD9ttLA
  artifact: deploy-out
  on:
    appveyor_repo_tag: true
